# первоначальный список слов
# если встретили слово, то дальше не смотрим слова
words_dict = {
    'glitch': 4141,
    'is down': 332,
    'was down': 52,
    'technical problem': 174,
    'technical mistake': 11,
    'technical lapse': 0,
    'technical issue': 412,
    'technical bug': 0,
    'technical difficult': 45,
    'technical blow': 0,
    'technical error': 64,
    'technical malfunction': 3,
    'technical outage': 19,
    'technical defect': 3,
    'software problem': 42,
    'software mistake': 0,
    'software lapse': 0,
    'software issue': 35,
    'software bug': 106,
    'software difficult': 0,
    'software blow': 0,
    'software error': 34,
    'software malfunction': 2,
    'software outage': 17,
    'software defect': 13,
    'hardware problem': 18,
    'hardware mistake': 0,
    'hardware lapse': 0,
    'hardware issue': 15,
    'hardware bug': 2,
    'hardware difficult': 0,
    'hardware blow': 0,
    'hardware error': 0,
    'hardware malfunction': 1,
    'hardware outage': 0,
    'hardware defect': 4,
    'system problem': 35,
    'system mistake': 1,
    'system lapse': 0,
    'system issue': 54,
    'system bug': 3,
    'system difficult': 1,
    'system blow': 0,
    'system error': 39,
    'system malfunction': 11,
    'system outage': 218,
    'system defect': 1,
    'computer problem': 60,
    'computer mistake': 0,
    'computer lapse': 0,
    'computer issue': 55,
    'computer bug': 15,
    'computer difficult': 0,
    'computer blow': 3,
    'computer error': 43,
    'computer malfunction': 2,
    'computer outage': 220,
    'computer defect': 0
}

{'glitch': 4141, 'is down': 344, 'was down': 52, 'went down': 86, 'technical breakdown': 0, 'technical failure': 37, 'technical damage': 0, 'technical tech': 0, 'technical problem': 174, 'technical mistake': 11, 'technical lapse': 0, 'technical issue': 412, 'technical bug': 0, 'technical difficult': 50, 'technical blow': 0, 'technical error': 64, 'technical malfunction': 3, 'technical outage': 19, 'technical defect': 3, 'software breakdown': 0, 'software failure': 2, 'software damage': 0, 'software tech': 2, 'software problem': 48, 'software mistake': 0, 'software lapse': 0, 'software issue': 35, 'software bug': 107, 'software difficult': 0, 'software blow': 0, 'software error': 34, 'software malfunction': 2, 'software outage': 17, 'software defect': 13, 'hardware breakdown': 0, 'hardware failure': 14, 'hardware damage': 0, 'hardware tech': 1, 'hardware problem': 18, 'hardware mistake': 0, 'hardware lapse': 0, 'hardware issue': 15, 'hardware bug': 2, 'hardware difficult': 0, 'hardware blow': 0, 'hardware error': 0, 'hardware malfunction': 1, 'hardware outage': 0, 'hardware defect': 4, 'system breakdown': 14, 'system failure': 234, 'system damage': 2, 'system tech': 0, 'system problem': 35, 'system mistake': 1, 'system lapse': 0, 'system issue': 55, 'system bug': 3, 'system difficult': 1, 'system blow': 0, 'system error': 39, 'system malfunction': 11, 'system outage': 218, 'system defect': 1, 'computer breakdown': 1, 'computer failure': 60, 'computer damage': 0, 'computer tech': 8, 'computer problem': 60, 'computer mistake': 0, 'computer lapse': 0, 'computer issue': 55, 'computer bug': 27, 'computer difficult': 0, 'computer blow': 3, 'computer error': 43, 'computer malfunction': 2, 'computer outage': 220, 'computer defect': 0, 'tech breakdown': 0, 'tech failure': 14, 'tech damage': 0, 'tech tech': 6, 'tech problem': 39, 'tech mistake': 0, 'tech lapse': 0, 'tech issue': 33, 'tech bug': 0, 'tech difficult': 0, 'tech blow': 1, 'tech error': 8, 'tech malfunction': 2, 'tech outage': 3, 'tech defect': 0}

